[project]
name = "jiangsu-safety-platform-skip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "streamlit>=1.48.1",
]
